name: autofix.ci

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    timeout-minutes: 10
    env:
      RUNNER_IMAGE: ubuntu-latest
    runs-on: ${{ env.RUNNER_IMAGE }}
    steps:
      - name: Checkout Code 🛎
        uses: actions/checkout@v4

      - name: Setup Bun 🌟
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node 📦
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'bun'

      - name: Install dependencies 📦
        run: bun install
